import { Currency, CurrencyType } from './currencies.types';

/**
 * Centralized currency configuration
 * This is the single source of truth for all supported currencies
 */
export const CURRENCIES_DATA: Currency[] = [
  // Cryptocurrency - Major coins
  {
    code: 'BTC',
    name: 'Bitcoin',
    type: CurrencyType.CRYPTO,
    icon: 'crypto:btc',
    displayOrder: 1,
    enabled: true,
    network: 'Bitcoin Mainnet',
    symbol: '₿',
    decimals: 8,
  },
  {
    code: 'ETH',
    name: 'Ethereum',
    type: CurrencyType.CRYPTO,
    icon: 'crypto:eth',
    displayOrder: 2,
    enabled: true,
    network: 'Ethereum Mainnet',
    symbol: 'Ξ',
    decimals: 18,
  },
  {
    code: 'USDT',
    name: 'Tether USD',
    type: CurrencyType.CRYPTO,
    icon: 'crypto:dai',
    displayOrder: 3,
    enabled: true,
    network: 'Multi-chain',
    symbol: '₮',
    decimals: 6,
  },
  {
    code: 'USDC',
    name: 'USD Coin',
    type: CurrencyType.CRYPTO,
    icon: 'crypto:usdc',
    displayOrder: 4,
    enabled: true,
    network: 'Multi-chain',
    symbol: 'USDC',
    decimals: 6,
  },
  {
    code: 'BNB',
    name: 'Binance Coin',
    type: CurrencyType.CRYPTO,
    icon: 'crypto:bnb',
    displayOrder: 5,
    enabled: true,
    network: 'BNB Chain',
    symbol: 'BNB',
    decimals: 18,
  },
  {
    code: 'SOL',
    name: 'Solana',
    type: CurrencyType.CRYPTO,
    icon: 'crypto:sol',
    displayOrder: 6,
    enabled: true,
    network: 'Solana',
    symbol: 'SOL',
    decimals: 9,
  },
  {
    code: 'ADA',
    name: 'Cardano',
    type: CurrencyType.CRYPTO,
    icon: 'crypto:ada',
    displayOrder: 7,
    enabled: true,
    network: 'Cardano',
    symbol: 'ADA',
    decimals: 6,
  },
  {
    code: 'XRP',
    name: 'Ripple',
    type: CurrencyType.CRYPTO,
    icon: 'crypto:xrp',
    displayOrder: 8,
    enabled: true,
    network: 'XRP Ledger',
    symbol: 'XRP',
    decimals: 6,
  },
  {
    code: 'DOGE',
    name: 'Dogecoin',
    type: CurrencyType.CRYPTO,
    icon: 'crypto:doge',
    displayOrder: 9,
    enabled: true,
    network: 'Dogecoin',
    symbol: 'Ð',
    decimals: 8,
  },
  {
    code: 'MATIC',
    name: 'Polygon',
    type: CurrencyType.CRYPTO,
    icon: 'crypto:matic',
    displayOrder: 10,
    enabled: true,
    network: 'Polygon',
    symbol: 'POL',
    decimals: 18,
  },
  {
    code: 'LTC',
    name: 'Litecoin',
    type: CurrencyType.CRYPTO,
    icon: 'crypto:ltc',
    displayOrder: 11,
    enabled: true,
    network: 'Litecoin',
    symbol: 'Ł',
    decimals: 8,
  },
  {
    code: 'TRX',
    name: 'Tronix',
    type: CurrencyType.CRYPTO,
    icon: 'crypto:trx',
    displayOrder: 12,
    enabled: true,
    network: 'Tron',
    symbol: 'TRX',
    decimals: 6,
  },
  {
    code: 'LINK',
    name: 'Chainlink',
    type: CurrencyType.CRYPTO,
    icon: 'crypto:link',
    displayOrder: 13,
    enabled: true,
    network: 'Ethereum',
    symbol: 'LINK',
    decimals: 18,
  },
  {
    code: 'BCH',
    name: 'Bitcoin Cash',
    type: CurrencyType.CRYPTO,
    icon: 'crypto:bch',
    displayOrder: 14,
    enabled: true,
    network: 'Bitcoin Cash',
    symbol: 'BCH',
    decimals: 8,
  },
  {
    code: 'SHIB',
    name: 'Shiba Inu',
    type: CurrencyType.CRYPTO,
    icon: 'crypto:shib',
    displayOrder: 15,
    enabled: true,
    network: 'Ethereum',
    symbol: 'SHIB',
    decimals: 18,
  },

  // Platform-specific tokens
  {
    code: 'MBX',
    name: 'MINT Bucks',
    type: CurrencyType.CRYPTO,
    icon: 'mint:header-wallet',
    displayOrder: 16,
    enabled: true,
    network: 'Mint',
    symbol: 'MBX',
    decimals: 2,
  },
  {
    code: 'SPN',
    name: 'Spins',
    type: CurrencyType.CRYPTO,
    icon: 'mint:header-wallet',
    displayOrder: 17,
    enabled: true,
    network: 'Mint',
    symbol: 'SPN',
    decimals: 2,
  },
  {
    code: 'RTP',
    name: 'RTP',
    type: CurrencyType.CRYPTO,
    icon: 'mint:header-wallet',
    displayOrder: 18,
    enabled: true,
    network: 'Mint',
    symbol: 'RTP',
    decimals: 2,
  },
  {
    code: 'XPP',
    name: 'XPP',
    type: CurrencyType.CRYPTO,
    icon: 'mint:header-wallet',
    displayOrder: 19,
    enabled: true,
    network: 'Mint',
    symbol: 'XPP',
    decimals: 2,
  },
  {
    code: 'POL',
    name: 'Polygon',
    type: CurrencyType.CRYPTO,
    icon: 'crypto:matic',
    displayOrder: 20,
    enabled: true,
    network: 'Polygon',
    symbol: 'POL',
    decimals: 18,
  },

  // Fiat currencies - Major currencies
  {
    code: 'USD',
    name: 'US Dollar',
    type: CurrencyType.FIAT,
    icon: 'flag:usd',
    displayOrder: 100,
    enabled: true,
    symbol: '$',
    decimals: 2,
  },
  {
    code: 'EUR',
    name: 'Euro',
    type: CurrencyType.FIAT,
    icon: 'flag:eur',
    displayOrder: 101,
    enabled: true,
    symbol: '€',
    decimals: 2,
  },
  {
    code: 'GBP',
    name: 'British Pound',
    type: CurrencyType.FIAT,
    icon: 'flag:gbp',
    displayOrder: 102,
    enabled: true,
    symbol: '£',
    decimals: 2,
  },
  {
    code: 'JPY',
    name: 'Japanese Yen',
    type: CurrencyType.FIAT,
    icon: 'flag:jpy',
    displayOrder: 103,
    enabled: true,
    symbol: '¥',
    decimals: 0,
  },
  {
    code: 'CNY',
    name: 'Chinese Yuan',
    type: CurrencyType.FIAT,
    icon: 'flag:cny',
    displayOrder: 104,
    enabled: true,
    symbol: '¥',
    decimals: 2,
  },

  // Other fiat currencies
  {
    code: 'CAD',
    name: 'Canadian Dollar',
    type: CurrencyType.FIAT,
    icon: 'flag:cad',
    displayOrder: 105,
    enabled: true,
    symbol: 'C$',
    decimals: 2,
  },
  {
    code: 'AUD',
    name: 'Australian Dollar',
    type: CurrencyType.FIAT,
    icon: 'flag:aud',
    displayOrder: 106,
    enabled: true,
    symbol: 'A$',
    decimals: 2,
  },
  {
    code: 'NZD',
    name: 'New Zealand Dollar',
    type: CurrencyType.FIAT,
    icon: 'flag:nzd',
    displayOrder: 107,
    enabled: true,
    symbol: 'NZ$',
    decimals: 2,
  },
  {
    code: 'BRL',
    name: 'Brazilian Real',
    type: CurrencyType.FIAT,
    icon: 'flag:brl',
    displayOrder: 108,
    enabled: true,
    symbol: 'R$',
    decimals: 2,
  },
  {
    code: 'KRW',
    name: 'South Korean Won',
    type: CurrencyType.FIAT,
    icon: 'flag:krw',
    displayOrder: 109,
    enabled: true,
    symbol: '₩',
    decimals: 0,
  },
  {
    code: 'IDR',
    name: 'Indonesian Rupiah',
    type: CurrencyType.FIAT,
    icon: 'flag:idr',
    displayOrder: 110,
    enabled: true,
    symbol: 'Rp',
    decimals: 0,
  },
  {
    code: 'CLP',
    name: 'Chilean Peso',
    type: CurrencyType.FIAT,
    icon: 'flag:clp',
    displayOrder: 111,
    enabled: true,
    symbol: 'CLP$',
    decimals: 0,
  },
  {
    code: 'MXN',
    name: 'Mexican Peso',
    type: CurrencyType.FIAT,
    icon: 'flag:mxn',
    displayOrder: 112,
    enabled: true,
    symbol: 'MX$',
    decimals: 2,
  },
  {
    code: 'HKD',
    name: 'Hong Kong Dollar',
    type: CurrencyType.FIAT,
    icon: 'flag:hkd',
    displayOrder: 113,
    enabled: true,
    symbol: 'HK$',
    decimals: 2,
  },
  {
    code: 'TWD',
    name: 'Taiwan Dollar',
    type: CurrencyType.FIAT,
    icon: 'flag:twd',
    displayOrder: 114,
    enabled: true,
    symbol: 'NT$',
    decimals: 2,
  },
  {
    code: 'VND',
    name: 'Vietnamese Dong',
    type: CurrencyType.FIAT,
    icon: 'flag:vnd',
    displayOrder: 115,
    enabled: true,
    symbol: '₫',
    decimals: 0,
  },
];

