packages:
  - apps/*
  - packages/*
  - '!apps/_*'
  - '!packages/_*'

catalog:
  '@changesets/cli': ^2.27.10
  '@eslint/js': ^9.23.0
  '@rollup/plugin-node-resolve': ^15.3.0
  '@stylistic/eslint-plugin-js': ^4.2.0
  '@stylistic/eslint-plugin-ts': ^4.2.0
  '@swc/core': ^1.11.24
  '@tailwindcss/postcss': ^4.1.4
  '@tanstack/react-query': ^5.80.6
  '@telegram-apps/sdk-react': ^3.2.4
  '@tonconnect/ui-react': ^2.1.0
  '@turbo/gen': ^2.5.0
  '@types/cookie-parser': ^1.4.9
  '@types/eslint__js': ^8.42.3
  '@types/express': ^5.0.1
  '@types/find': ^0.2.4
  '@types/fs-extra': ^11.0.4
  '@types/jsonfile': ^6.1.4
  '@types/module-alias': ^2.0.4
  '@types/morgan': ^1.9.9
  '@types/node': ^22
  '@types/react': ^19
  '@types/react-dom': ^19
  '@types/supertest': ^6.0.3
  '@typescript-eslint/eslint-plugin': ^8.34.1
  '@typescript-eslint/parser': ^8.34.1
  '@vitest/coverage-v8': ^2.1.6
  '@vitejs/plugin-react': ^4.3.4
  '@vitest/ui': ^2.1.6
  browser-sync: ^2.27.5
  canvas: ^2.11.2
  canvas-confetti: ^1.9.3
  cookie-parser: ^1.4.7
  dayjs: ^1.11.13
  dotenv: ^16.5.0
  eruda: ^3.4.1
  esbuild: ^0.15.11
  eslint: ^9.25.1
  eslint-config-next: ^15.3.1
  eslint-import-resolver-typescript: ^3.7.0
  eslint-plugin-import: ^2.31.0
  eslint-plugin-n: ^17.17.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.1.0
  eslint-plugin-react-refresh: ^0.4.19
  eslint-plugin-perfectionist: ^4.4.0
  eslint-plugin-unused-imports: ^4.1.4
  express: ^5.1.0
  find: ^0.3.0
  fs-extra: ^11.3.0
  globals: ^16.0.0
  grammy: ^1.36.1
  helmet: ^8.1.0
  husky: ^9.1.7
  i18next: ^24.2.3
  i18next-browser-languagedetector: ^8.0.4
  i18next-resources-to-backend: ^1.2.1
  inserturlparams: ^2.0.5
  jest: ^27.4.3
  jest-canvas-mock: ^2.5.1
  jet-env: ^1.1.4
  jet-logger: ^2.0.1
  jet-paths: ^1.1.0
  jet-validators: ^1.4.0
  jiti: ^2.4.2
  jsonfile: ^6.1.0
  module-alias: ^2.2.3
  morgan: ^1.10.0
  next: ^15.4.4
  next-intl: ^4.1.0
  next-i18next: ^15.4.2
  nodemon: ^3.1.10
  normalize.css: ^8.0.1
  postcss: ^8
  prettier: ^3.5.3
  react: ^19.1.0
  react-dom: ^19.1.0
  rimraf: ^6.0.1
  spin-wheel: ^5.0.2
  supertest: ^7.1.0
  tailwindcss: ^4.1.5
  ts-loader: ^9.5.2
  ts-node: ^10.9.2
  ts-node-dev: ^2.0.0
  tsconfig-paths: ^4.2.0
  tslib: ^2.8.1
  tsx: ^4.19.3
  typescript: ^5
  typescript-eslint: ^8.31.1
  turbo: ^2.5.0
  vite: ^6.3.4
  vitest: ^3.1.2
  vite-plugin-dts: ^4.5.3
  vite-plugin-mkcert: ^1.17.8
  vite-plugin-solid: ^2.11.6
  vite-tsconfig-paths: ^5.1.4

catalogs:
  mui:
    '@auth0/auth0-react': ^2.3.0
    '@dnd-kit/core': ^6.3.1
    '@dnd-kit/sortable': ^10.0.0
    '@dnd-kit/utilities': ^3.2.2
    '@emotion/cache': ^11.14.0
    '@emotion/react': ^11.14.0
    '@emotion/styled': ^11.14.0
    '@fontsource-variable/dm-sans': ^5.2.5
    '@fontsource-variable/inter': ^5.2.5
    '@fontsource-variable/nunito-sans': ^5.2.5
    '@fontsource-variable/public-sans': ^5.2.5
    '@fontsource/barlow': ^5.2.5
    '@fullcalendar/core': ^6.1.15
    '@fullcalendar/daygrid': ^6.1.15
    '@fullcalendar/interaction': ^6.1.15
    '@fullcalendar/list': ^6.1.15
    '@fullcalendar/react': ^6.1.15
    '@fullcalendar/timegrid': ^6.1.15
    '@fullcalendar/timeline': ^6.1.15
    '@hookform/resolvers': ^4.1.3
    '@iconify/react': 5.2.1
    '@mui/lab': 7.0.0-beta.13
    '@mui/material': 7.1.1
    '@mui/material-nextjs': 7.1.1
    '@mui/system': 7.1.1
    '@mui/x-data-grid': ^7.28.2
    '@mui/x-date-pickers': ^7.28.2
    '@mui/x-tree-view': ^7.28.1
    '@react-pdf/renderer': ^4.3.0
    '@supabase/supabase-js': ^2.49.3
    '@svgr/webpack': ^8.1.0
    '@tiptap/core': ^2.11.6
    '@tiptap/extension-code-block': ^2.11.6
    '@tiptap/extension-code-block-lowlight': ^2.11.6
    '@tiptap/extension-image': ^2.11.6
    '@tiptap/extension-link': ^2.11.6
    '@tiptap/extension-placeholder': ^2.11.6
    '@tiptap/extension-text-align': ^2.11.6
    '@tiptap/extension-underline': ^2.11.6
    '@tiptap/pm': ^2.11.6
    '@tiptap/react': ^2.11.6
    '@tiptap/starter-kit': ^2.11.6
    '@types/autosuggest-highlight': ^3.2.3
    '@types/nprogress': ^0.2.3
    '@types/stylis': ^4.2.7
    '@types/turndown': ^5.0.5
    apexcharts: ^4.5.0
    autosuggest-highlight: ^3.3.4
    aws-amplify: ^6.14.1
    axios: ^1.8.4
    embla-carousel: ^8.5.2
    embla-carousel-auto-height: ^8.5.2
    embla-carousel-auto-scroll: ^8.5.2
    embla-carousel-autoplay: ^8.5.2
    embla-carousel-fade: ^8.5.2
    embla-carousel-react: ^8.5.2
    es-toolkit: ^1.34.1
    firebase: ^11.5.0
    framer-motion: ^12.6.1
    lowlight: ^3.3.0
    mapbox-gl: ^3.10.0
    minimal-shared: ^1.0.7
    mui-one-time-password-input: ^4.0.1
    nprogress: ^0.2.0
    react-apexcharts: ^1.7.0
    react-dropzone: ^14.3.8
    react-map-gl: ^8.0.2
    react-markdown: ^10.1.0
    react-organizational-chart: ^2.2.1
    react-phone-number-input: ^3.4.12
    rehype-highlight: ^7.0.2
    rehype-raw: ^7.0.0
    remark-gfm: ^4.0.1
    simplebar-react: 3.3.0
    sonner: ^2.0.2
    stylis: ^4.3.6
    stylis-plugin-rtl: ^2.1.1
    swr: ^2.3.3
    turndown: ^7.2.0
    yet-another-react-lightbox: ^3.21.8
    zod: ^3.24.2
