import type { Mission } from './missions.types';

export const STATIC_MISSIONS: Mission[] = [
  {
    id: '1',
    title: 'Follow us on X',
    exp: 150,
    tickets: 15,
    label: 'Label Here',
    status: 'available',
    actionLabel: 'Go',
  },
  {
    id: '2',
    title: 'Refer a Friend',
    exp: 150,
    tickets: 15,
    label: 'Label Here',
    status: 'available',
    actionLabel: 'Go',
  },
  {
    id: '3',
    title: 'Refer 5 Friends',
    exp: 150,
    tickets: 15,
    label: 'Label Here',
    status: 'completed',
    actionLabel: 'Completed',
  },
  {
    id: '4',
    title: 'Use 5 Daily Bonus Plays',
    exp: 150,
    tickets: 15,
    label: 'Label Here',
    status: 'completed',
    actionLabel: 'Completed',
  },
  {
    id: '5',
    title: 'Use 10 Daily Bonus Plays',
    exp: 150,
    tickets: 15,
    label: 'Label Here',
    status: 'claimable',
    actionLabel: 'Claim',
  },
  {
    id: '6',
    title: 'Wager 100 Coins in the Casino',
    exp: 150,
    tickets: 15,
    label: 'Label Here',
    status: 'available',
    actionLabel: 'Go',
  },
  {
    id: '7',
    title: 'Wager 500 Coins in the Casino',
    exp: 150,
    tickets: 15,
    label: 'Label Here',
    status: 'available',
    actionLabel: 'Go',
  },
  {
    id: '8',
    title: 'Wager 1000 Coins in the Casino',
    exp: 150,
    tickets: 15,
    label: 'Label Here',
    status: 'available',
    actionLabel: 'Go',
  },
];
